version: 0.1
phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
      - unzip terraform_0.11.8_linux_amd64.zip -d /bin
      - rm -f terraform_0.11.8_linux_amd64.zip
      - wget -P /bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.14.11/terragrunt_linux_amd64
      - chmod +x /bin/terragrunt
  build:
    commands:
      - cd ./deploy/cd && terragrunt apply
      - cd ./deploy/app && terragrunt apply