version: 0.1
phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.11.8/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /bin
      - rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.14.11/terragrunt_linux_amd64 /bin/terragrunt
      - chmod +x /bin/terragrunt
      - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
      - sudo apt-get install -y nodejs 
  build:
    commands:
      - pushd ./app
      - npm test
      - popd
  build:
    commands:
      - cd ./deploy
      - pushd ./cd
      - terragrunt apply
      - popd; pushd ./app
      - terragrunt apply