version: 0.2
env:
  variables:
    AWS_REGION: 
phases:
  install:
    commands:
      - wget https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
      - unzip terraform_0.11.11_linux_amd64.zip -d /bin
      - rm -f terraform_0.11.11_linux_amd64.zip
      - wget -O /bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.16.3/terragrunt_linux_amd64
      - chmod +x /bin/terragrunt
  build:
    commands:
      - cd ./deploy/cd && terragrunt apply --terragrunt-non-interactive
      - cd ./deploy/app && terragrunt apply --terragrunt-non-interactive